sonar.projectKey=next-friday_friday-sandbox
sonar.organization=next-friday

sonar.sources=packages/react/src,packages/eslint-config,packages/typescript-config,packages/styles/src
sonar.tests=packages/react/src
sonar.test.inclusions=**/*.test.{ts,tsx},**/*.stories.{ts,tsx}

sonar.javascript.lcov.reportPaths=packages/react/coverage/lcov.info
sonar.exclusions=**/dist/**,**/storybook-static/**,**/node_modules/**,**/.turbo/**,**/coverage/**

sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
