// Codegen: expand tokens/default.spec.json through formulas.ts into the
// generated `--fri-*` token CSS. Run via `pnpm --filter @friday-sandbox/styles codegen`.
// Generated files are committed but hand-edits are overwritten — change the spec
// or scripts/formulas.ts instead.
//
// Emits, all from one source (formulas.ts):
//   src/theme/tokens.css      @layer theme — base per [data-theme] scope + the
//                             derived system under `:root, [data-theme]` so a
//                             nested scope recomputes its own color-mix.
//   src/theme/tailwind.css    UNLAYERED @theme inline — maps Tailwind's
//                             --color-* / --radius-* to the --fri-* tokens.
//   src/theme/registered.css  @property typing (static initial-value).
//   src/theme-template.css    the Tier-1 override starter a consumer copies.
//   design.md                 the human + machine contract.

import { writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

import {
  P,
  BRAND_ROLES,
  LADDER,
  ladder,
  MIX_RATIOS,
  SURFACES,
  surface,
  surfaceForeground,
  FIELD_EXTRAS,
  TEXT_TIERS,
  textTier,
  BORDER_TIERS,
  borderTier,
  SCROLL_THUMB,
  POINTERS,
  radiusScale,
  RADIUS_ARCHETYPE,
  SIZE_ARCHETYPE,
  SPACING_SCALE,
  DURATION,
  EASING,
  Z_INDEX,
  GLOBALS,
  GAP_SCALE,
  GROUND_DARK,
  oklch,
} from "./formulas.ts";
import { chooseForegrounds } from "./contrast.ts";
import { loadSpec } from "./spec.ts";
import type { BrandRole } from "./types.ts";

const here = path.dirname(fileURLToPath(import.meta.url));
const package_ = path.join(here, "..");
const spec = loadSpec();

const HEADER =
  "/* GENERATED by scripts/codegen.ts from tokens/default.spec.json — do not edit by hand. */\n";
const FG = chooseForegrounds(spec);
const RADIUS = radiusScale(spec.radius ?? "0.875rem");
const BORDER_WIDTH = spec.border ?? "1px";
const v = (name: string): string => `var(${P}${name})`;
const decl = (name: string, value: string): string =>
  `  ${P}${name}: ${value};`;
const BORDER_NAME: Record<string, string> = {
  strong: "border-strong",
  default: "border",
  subtle: "border-subtle",
};
/**
 * The irregular CSS-var name a border tier emits (border, border-strong, …).
 */
const borderName = (tier: string): string => {
  const name = BORDER_NAME[tier];
  if (name == undefined) throw new Error(`unknown border tier: ${tier}`);
  return name;
};

/** The Tier-1 base block: the small surface a consumer overrides. */
function baseLight() {
  const c = spec.color;
  const L = ["  color-scheme: light;", "", "  /* Ground */"];
  L.push(decl("background", oklch(c.background)));
  L.push(decl("foreground", oklch(c.foreground)));
  L.push(
    decl("neutral", oklch(c.neutral)),
    "",
    "  /* Brand and status roles (background-independent fills) */",
  );
  for (const role of BRAND_ROLES) {
    L.push(decl(role, oklch(c[role])));
    L.push(decl(`${role}-foreground`, FG[role]));
  }
  L.push(
    "",
    "  /* Focus ring — defaults to primary; override for an a11y focus colour */",
  );
  L.push(decl("ring", v("primary")), "", "  /* Radius scale */");
  for (const [k, value] of Object.entries(RADIUS))
    L.push(decl(`radius-${k}`, value));
  L.push("", "  /* Spacing scale */");
  for (const [k, value] of Object.entries(SPACING_SCALE))
    L.push(decl(`spacing-${k}`, value));
  L.push("", "  /* Type */");
  L.push(
    decl(
      "font-family-sans",
      spec.fontSans || "ui-sans-serif, system-ui, sans-serif",
    ),
  );
  L.push(
    decl(
      "font-family-mono",
      spec.fontMono || "ui-monospace, SFMono-Regular, Menlo, monospace",
    ),
    "",
    "  /* Motion */",
  );
  for (const [k, value] of Object.entries(DURATION))
    L.push(decl(`duration-${k}`, value));
  for (const [k, value] of Object.entries(EASING))
    L.push(decl(`easing-${k}`, value));
  L.push("", "  /* Stacking */");
  for (const [k, value] of Object.entries(Z_INDEX))
    L.push(decl(`z-${k}`, value));
  L.push("", "  /* Global scalars */");
  for (const [k, value] of Object.entries(GLOBALS))
    L.push(decl(k, k === "border-width" ? BORDER_WIDTH : value));
  return L.join("\n");
}

/** The dark block: only the tokens that flip with the ground. */
function baseDark() {
  const D = ["  color-scheme: dark;", "", "  /* Ground flips */"];
  D.push(decl("background", GROUND_DARK.background));
  D.push(
    decl("foreground", GROUND_DARK.foreground),
    "",
    "  /* Accent flips with the ground */",
  );
  D.push(decl("accent", GROUND_DARK.accent));
  D.push(decl("accent-foreground", GROUND_DARK["accent-foreground"]));
  return D.join("\n");
}

/** The Tier-2 derived system — emitted per scope so nested themes recompute. */
function derived() {
  const D = [
    "  /* Interaction mix ratios (shared; a future intensity knob scales these) */",
  ];
  for (const [k, value] of Object.entries(MIX_RATIOS)) D.push(decl(k, value));
  D.push("", "  /* Interaction ladder — per role × rung */");
  for (const role of BRAND_ROLES)
    for (const rung of LADDER)
      D.push(decl(`${role}-${rung.suffix}`, ladder(role, rung.suffix)));
  D.push("", "  /* Surfaces (derived from the ground) */");
  for (const name of SURFACES) {
    D.push(decl(name, surface(name)));
    D.push(decl(`${name}-foreground`, surfaceForeground(name)));
  }
  D.push(decl("overlay", surface("overlay")));
  for (const [k, value] of Object.entries(FIELD_EXTRAS)) D.push(decl(k, value));
  D.push("", "  /* Text emphasis tiers */");
  for (const name of Object.keys(TEXT_TIERS))
    D.push(decl(`foreground-${name}`, textTier(name)));
  D.push("", "  /* Border / line tiers */");
  for (const name of Object.keys(BORDER_TIERS))
    D.push(decl(borderName(name), borderTier(name)));
  for (const [k, value] of Object.entries(SCROLL_THUMB)) D.push(decl(k, value));
  D.push("", "  /* Pointers */");
  for (const [k, value] of Object.entries(POINTERS)) D.push(decl(k, value));
  D.push(
    "",
    "  /* Geometry archetypes — role-led `--fri-<archetype>-radius` / `-size`. */",
    "  /* Radius aliases the t-shirt scale; size is the default block-axis dimension. */",
  );
  for (const [k, alias] of Object.entries(RADIUS_ARCHETYPE))
    D.push(decl(`${k}-radius`, v(`radius-${alias}`)));
  for (const [k, value] of Object.entries(SIZE_ARCHETYPE))
    D.push(decl(`${k}-size`, value));
  D.push("", "  /* Layout gap aliases the spacing scale */");
  for (const k of GAP_SCALE) D.push(decl(`gap-${k}`, v(`spacing-${k}`)));
  return D.join("\n");
}

/** The full `@layer theme` token CSS: the light and dark base blocks plus the derived system. */
function buildTokens() {
  const light = `:root,\n.light,\n[data-theme="light"] {\n${baseLight()}\n}`;
  const dark = `.dark,\n[data-theme="dark"] {\n${baseDark()}\n}`;
  const der = `:root,\n[data-theme] {\n${derived()}\n}`;
  return `${HEADER}@layer theme {\n${light}\n\n${dark}\n\n${der}\n}\n`;
}

/**
 * The Tailwind `--color-<utility>` map: each utility name a component references
 * (`bg-separator`, `text-primary`, …) paired with the `--fri-*` token it reads.
 * Most are identity; a few utility names differ from the token (separator).
 */
function colorMap() {
  const m = [
    ["background", "background"],
    ["foreground", "foreground"],
    ["neutral", "neutral"],
    ["ring", "ring"],
    ["link", "link"],
    ["overlay", "overlay"],
    ["border", "border"],
    ["border-strong", "border-strong"],
    ["border-subtle", "border-subtle"],
    ["separator", "border-subtle"],
    ["scroll-thumb", "scroll-thumb"],
    ["scroll-thumb-hover", "scroll-thumb-hover"],
    ["scroll-track", "scroll-track"],
    ["foreground-muted", "foreground-muted"],
    ["foreground-faint", "foreground-faint"],
  ];
  for (const role of BRAND_ROLES) {
    m.push([role, role], [`${role}-foreground`, `${role}-foreground`]);
    for (const rung of LADDER)
      m.push([`${role}-${rung.suffix}`, `${role}-${rung.suffix}`]);
  }
  for (const name of SURFACES)
    m.push([name, name], [`${name}-foreground`, `${name}-foreground`]);
  m.push(
    ["field-border-color", "field-border-color"],
    ["field-placeholder", "field-placeholder"],
  );
  return m;
}

/** UNLAYERED `@theme` inline so Tailwind v4 reads it at the theme-directive level. */
function buildTailwind() {
  const L = [];
  for (const [utility, token] of colorMap())
    L.push(`  --color-${utility}: var(${P}${token});`);
  for (const k of Object.keys(RADIUS))
    L.push(`  --radius-${k}: var(${P}radius-${k});`);
  for (const k of Object.keys(SPACING_SCALE))
    L.push(`  --spacing-${k}: var(${P}spacing-${k});`);
  L.push(
    `  --font-sans: var(${P}font-family-sans);`,
    `  --font-mono: var(${P}font-family-mono);`,
  );
  return `${HEADER}@theme inline {\n${L.join("\n")}\n}\n`;
}

/** Property typing for the base color tokens. Static initial-value (no var/color-mix). */
function buildRegistered() {
  const c = spec.color;
  const L: string[] = [];
  const reg = (name: string, init: string) =>
    L.push(
      `@property ${P}${name} {\n  syntax: "<color>";\n  inherits: true;\n  initial-value: ${init};\n}`,
    );
  for (const role of BRAND_ROLES) {
    reg(role, oklch(c[role]));
    reg(`${role}-foreground`, FG[role]);
  }
  reg("background", oklch(c.background));
  reg("foreground", oklch(c.foreground));
  reg("neutral", oklch(c.neutral));
  return `${HEADER}${L.join("\n\n")}\n`;
}

/** The Tier-1 override starter a consumer copies into their global CSS. */
function buildTemplate() {
  const c = spec.color;
  const line = (name: string, value: string): string =>
    `  ${P}${name}: ${value};`;
  const L: string[] = [
    "/* GENERATED by scripts/codegen.ts from tokens/default.spec.json. This",
  ];
  L.push(
    "   file is overwritten on every codegen run, so do not edit it here.",
    '   Copy it into your global CSS after `@import "@friday-sandbox/styles"`,',
  );
  L.push(
    "   then edit the copy. Set only these base tokens; the system derives",
    "   the ladder, surfaces, and tiers from them. Override a foreground",
    "   together with its fill so the text stays legible. */",
    "",
  );
  L.push(':root,\n[data-theme="light"] {', "  /* Brand */");
  const brand: BrandRole[] = ["primary", "secondary", "accent"];
  for (const role of brand) {
    L.push(line(role, oklch(c[role])));
    L.push(line(`${role}-foreground`, FG[role]));
  }
  L.push("  /* Status */");
  const status: BrandRole[] = ["info", "success", "warning", "danger"];
  for (const role of status) {
    L.push(line(role, oklch(c[role])));
    L.push(line(`${role}-foreground`, FG[role]));
  }
  L.push("  /* Ground */");
  L.push(line("background", oklch(c.background)));
  L.push(line("foreground", oklch(c.foreground)));
  L.push(line("neutral", oklch(c.neutral)), "  /* Focus, geometry, type */");
  L.push(line("ring", oklch(c.primary)));
  L.push(line("radius-md", RADIUS.md));
  L.push(
    line("border-width", BORDER_WIDTH),
    "}",
    "",
    '.dark,\n[data-theme="dark"] {',
  );
  L.push("  /* Only the ground flips; brand and status fills carry across. */");
  L.push(line("background", GROUND_DARK.background));
  L.push(line("foreground", GROUND_DARK.foreground), "}");
  return `${L.join("\n")}\n`;
}

/** The generated `design.md` token contract. */
function buildDesignMd() {
  const rungs = LADDER.map((r) => r.suffix).join(", ");
  return `---
generated: true
namespace: --fri-*
pipeline: spec -> validate (schema) -> derive (formulas.ts) -> emit (tokens.css, tailwind.css, registered.css)
---

# Friday Design System token contract

Generated from \`tokens/default.spec.json\` through \`scripts/formulas.ts\`. Every
token is \`--fri-*\` prefixed; every colour mix is \`color-mix(in oklab, …)\`. Edit
the spec or the formula table, never the generated CSS.

## Two tiers

- **Tier 1 (consumer base):** brand \`primary/secondary/accent\`, status \`info/success/warning/danger\` (each + \`-foreground\`); ground \`background/foreground/neutral\`; \`ring\`; the radius and spacing scales; type, motion, and z-index. A consumer sets these; the system derives the rest.
- **Tier 2 (derived):** the ${LADDER.length}-rung interaction ladder (${rungs}) per brand role; surfaces (card, popover, field, fill, fill-strong, inverse, overlay) derived from the ground; text tiers (foreground-muted, foreground-faint); border tiers (border-strong, border, border-subtle). Public and overridable, but names freeze only at the first stable release.

## Emission

Token definitions live in \`@layer theme\`; the derived system is emitted under
\`:root, [data-theme]\` so a nested \`[data-theme]\` scope recomputes its own
\`color-mix\` against that scope's ground. The \`@theme inline\` Tailwind map is
emitted unlayered in \`tailwind.css\`. \`@property\` registers the base colours as
progressive enhancement with a static \`initial-value\`.

## Declared grammar exceptions

These irregularities are intentional and declared, not accidental:

- **Scale vocabularies.** \`spacing\` is the full scale (2xs to 4xl). \`gap\` is a deliberate subset of it (xs to xl). \`radius\` carries the semantic endpoints \`none\` and \`full\` around an xs to xl range. The differences are by design, not omissions.
- **Dark re-declarations.** \`background\`, \`foreground\`, \`accent\` and \`accent-foreground\` are emitted twice, once light and once under the dark scope, because they flip with the ground.
- **Geometry archetypes.** \`--fri-<archetype>-radius\` and \`--fri-<archetype>-size\` (action, field, box, feedback) are single default values, role-led to mirror the colour grammar. \`size\` is the default block-axis control dimension, that is a control height, not an icon size, a width, or a spacing unit. Per-size variants are produced inside each component from local \`--_*\` variables and are not public tokens.
- **Interaction ladder state coverage.** \`soft\` and \`surface\` are stateful fills with base, hover and pressed rungs. \`tint\` is an interaction-only overlay with hover and pressed and no base, by design. \`border\` and \`outline-border\` are static line colours with no interaction rungs.
- **Private variables.** Custom properties beginning \`--_\` are component-internal and carry no SemVer guarantee. Only \`--fri-*\` is the public contract.
`;
}

const out = {
  "src/theme/tokens.css": buildTokens(),
  "src/theme/tailwind.css": buildTailwind(),
  "src/theme/registered.css": buildRegistered(),
  "src/theme-template.css": buildTemplate(),
  "design.md": buildDesignMd(),
};
for (const [relativePath, content] of Object.entries(out))
  writeFileSync(path.join(package_, relativePath), content);
const all = Object.keys(out).join(" ");
execSync(`pnpm exec prettier --write ${all}`, {
  cwd: package_,
  stdio: "inherit",
});
console.log(`codegen: wrote + formatted ${all}`);
