// Codegen: expand tokens/default.spec.json through the formula table into the
// generated theme CSS. Run via `pnpm --filter @friday-sandbox/styles codegen`.
// Generated files (src/theme/color.css, src/theme/theme.css) are committed but
// hand-edits are overwritten — change the spec or scripts/formulas.js instead.

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  BRAND_ROLES,
  LADDER,
  ladderValue,
  MIX_RATIOS,
  LINE_RATIOS,
  GLOBALS,
  BUTTON_N,
  SCROLL_N,
  SPINNER_N,
  SEPARATOR_N,
  SCROLL_RATIOS,
  SPINNER_VALS,
  GROUND_DARK,
  SURFACE_FAMILY,
  oklch,
  lightDark,
} from "./formulas.js";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "..");
const spec = JSON.parse(
  readFileSync(join(pkg, "tokens/default.spec.json"), "utf8"),
);

const HEADER =
  "/* GENERATED by scripts/codegen.js from tokens/default.spec.json — do not edit by hand. */\n";
const FG_WHITE = "oklch(100% 0 0)";

function buildColor() {
  const c = spec.color;
  const L = [];
  L.push("  color-scheme: light;", "");
  L.push("  /* Ground */");
  L.push(
    `  --background: ${lightDark(oklch(c.background), GROUND_DARK.background)};`,
  );
  L.push(
    `  --foreground: ${lightDark(oklch(c.foreground), GROUND_DARK.foreground)};`,
  );
  L.push(`  --neutral: ${oklch(c.neutral)};`, "");
  L.push(
    "  /* Inverted surface pair (e.g. a tooltip): background/foreground swapped */",
  );
  L.push("  --surface: var(--foreground);");
  L.push("  --surface-foreground: var(--background);", "");
  L.push(
    "  /* Brand roles — single-valued (background-independent) except accent */",
  );
  for (const role of BRAND_ROLES) {
    if (role === "accent") {
      L.push(`  --accent: ${lightDark(oklch(c.accent), GROUND_DARK.accent)};`);
      L.push(
        `  --accent-foreground: ${lightDark(FG_WHITE, GROUND_DARK["accent-foreground"])};`,
      );
    } else {
      L.push(`  --${role}: ${oklch(c[role])};`);
      L.push(`  --${role}-foreground: ${FG_WHITE};`);
    }
  }
  L.push("");
  L.push(`  --ring: ${lightDark(oklch(c.primary), GROUND_DARK.ring)};`);
  L.push(`  --link: ${lightDark(oklch(c.primary), GROUND_DARK.link)};`, "");
  L.push(
    "  /* Surface family — shadcn-compatible vocabulary, no interaction ladder */",
  );
  for (const [name, light, dark] of SURFACE_FAMILY) {
    L.push(`  --${name}: ${lightDark(light, dark)};`);
  }
  L.push("");
  L.push("  /* Destructive aliases danger (danger owns the ladder) */");
  L.push("  --destructive: var(--danger);");
  L.push("  --destructive-foreground: var(--danger-foreground);");
  return `${HEADER}:root {\n${L.join("\n")}\n}\n\n.dark,\n[data-theme="dark"] {\n  color-scheme: dark;\n}\n`;
}

function buildTheme() {
  const L = [];
  L.push(
    "  /* Global scalars — consumed across utilities, base, and components */",
  );
  for (const [k, v] of Object.entries(GLOBALS)) L.push(`  --${k}: ${v};`);
  L.push("", "  /* Interaction mix ratios — shared across every color role */");
  for (const [k, v] of Object.entries(MIX_RATIOS)) L.push(`  --${k}: ${v};`);
  L.push("", "  /* Neutral-derived line colors */");
  for (const [k, v] of Object.entries(LINE_RATIOS)) L.push(`  --${k}: ${v};`);
  L.push(
    "  --border-color: color-mix(in oklab, var(--neutral), transparent var(--mix-border-line));",
  );
  L.push(
    "  --separator-color: color-mix(in oklab, var(--neutral), transparent var(--mix-separator-line));",
  );
  L.push(
    "",
    "  /* Color ladder — generated per role × rung (single source: formulas.js) */",
  );
  for (const role of BRAND_ROLES) {
    for (const rung of LADDER)
      L.push(`  --${role}-${rung.suffix}: ${ladderValue(role, rung)};`);
  }
  L.push(
    "",
    "  /* Action geometry — button sizes (step count drives height, padding, radius) */",
  );
  for (const [s, n] of Object.entries(BUTTON_N))
    L.push(`  --button-n-${s}: ${n};`);
  for (const s of Object.keys(BUTTON_N))
    L.push(
      `  --button-h-${s}: calc(var(--size-action) * var(--button-n-${s}));`,
    );
  for (const s of Object.keys(BUTTON_N))
    L.push(
      `  --button-px-${s}: calc(var(--button-h-${s}) / 2 - var(--size-action));`,
    );
  for (const s of Object.keys(BUTTON_N))
    L.push(
      `  --button-radius-${s}: calc(var(--radius-action) * var(--button-n-${s}) / var(--button-n-md));`,
    );
  for (const s of Object.keys(BUTTON_N))
    L.push(`  --button-spinner-${s}: calc(var(--button-h-${s}) / 2);`);
  L.push("", "  /* Scroll-area geometry + thumb colors */");
  for (const [s, n] of Object.entries(SCROLL_N))
    L.push(`  --scroll-area-n-${s}: ${n};`);
  for (const s of Object.keys(SCROLL_N))
    L.push(
      `  --scroll-area-thickness-${s}: calc(var(--size-box) * var(--scroll-area-n-${s}));`,
    );
  for (const [k, v] of Object.entries(SCROLL_RATIOS)) L.push(`  --${k}: ${v};`);
  L.push(
    "  --scroll-thumb: color-mix(in oklab, var(--neutral) var(--mix-scroll-thumb), transparent);",
  );
  L.push(
    "  --scroll-thumb-hover: color-mix(in oklab, var(--neutral) var(--mix-scroll-thumb-hover), transparent);",
  );
  L.push("  --scroll-track: transparent;");
  L.push("", "  /* Spinner geometry + gradient (rides currentColor) */");
  for (const [s, n] of Object.entries(SPINNER_N))
    L.push(`  --spinner-n-${s}: ${n};`);
  for (const s of Object.keys(SPINNER_N))
    L.push(
      `  --spinner-size-${s}: calc(var(--size-feedback) * var(--spinner-n-${s}));`,
    );
  L.push(`  --spinner-arc: ${SPINNER_VALS["spinner-arc"]};`);
  L.push(`  --spinner-thickness: ${SPINNER_VALS["spinner-thickness"]};`);
  L.push(`  --mix-spinner-track: ${SPINNER_VALS["mix-spinner-track"]};`);
  L.push(
    "  --spinner-track: color-mix(in oklab, currentColor var(--mix-spinner-track), transparent);",
  );
  L.push(
    "  --spinner-image: conic-gradient(currentColor var(--spinner-arc), var(--spinner-track) 0);",
  );
  L.push(
    "  --spinner-mask: radial-gradient(farthest-side, transparent calc(100% - var(--spinner-thickness)), black 0);",
  );
  L.push("", "  /* Separator geometry */");
  L.push(`  --separator-n: ${SEPARATOR_N};`);
  L.push("  --separator-thickness: var(--border);");
  L.push("  --separator-length: calc(var(--size-box) * var(--separator-n));");
  L.push(
    "",
    "  /* Layout gap scale — shared by flex and grid, derived from --space */",
  );
  L.push("  --gap-xs: var(--space);");
  L.push("  --gap-sm: calc(var(--space) * 2);");
  L.push("  --gap-md: calc(var(--space) * 4);");
  L.push("  --gap-lg: calc(var(--space) * 6);");
  L.push("  --gap-xl: calc(var(--space) * 8);");
  const imports =
    '@import "./registered.css";\n@import "./border.css";\n@import "./color.css";\n@import "./radius.css";\n@import "./typography.css";';
  return `${HEADER}${imports}\n\n:root {\n${L.join("\n")}\n}\n`;
}

// Register the knob tokens with @property so the theme builder gets typed,
// animatable, guarded inputs — and browsers without light-dark() fall back to
// the (light) initial-value instead of an invalid declaration.
function buildRegistered() {
  const c = spec.color;
  const L = [];
  const reg = (name, syntax, init) =>
    L.push(
      `@property --${name} {\n  syntax: "${syntax}";\n  inherits: true;\n  initial-value: ${init};\n}`,
    );
  for (const role of BRAND_ROLES) {
    reg(role, "<color>", oklch(c[role]));
    reg(`${role}-foreground`, "<color>", FG_WHITE);
  }
  reg("background", "<color>", oklch(c.background));
  reg("foreground", "<color>", oklch(c.foreground));
  reg("neutral", "<color>", oklch(c.neutral));
  for (const [name, light] of SURFACE_FAMILY) reg(name, "<color>", light);
  reg("space", "<length>", GLOBALS.space);
  reg("ring-width", "<length>", GLOBALS["ring-width"]);
  reg("ring-offset-width", "<length>", GLOBALS["ring-offset-width"]);
  reg("disabled-opacity", "<number>", GLOBALS["disabled-opacity"]);
  return `${HEADER}${L.join("\n\n")}\n`;
}

const out = [
  "src/theme/registered.css",
  "src/theme/color.css",
  "src/theme/theme.css",
];
writeFileSync(join(pkg, out[0]), buildRegistered());
writeFileSync(join(pkg, out[1]), buildColor());
writeFileSync(join(pkg, out[2]), buildTheme());
// Format with Prettier so generated output matches the committed style, keeping
// `pnpm build` idempotent (.prettierignore is protected, so we self-format).
execSync(`pnpm exec prettier --write ${out.join(" ")}`, {
  cwd: pkg,
  stdio: "inherit",
});
console.log(`codegen: wrote + formatted ${out.join(", ")}`);
