// Codegen: expand tokens/default.spec.json through the formula table into the
// generated theme CSS. Run via `pnpm --filter @friday-sandbox/styles codegen`.
// Generated files (src/theme/color.css, src/theme/theme.css) are committed but
// hand-edits are overwritten — change the spec or scripts/formulas.js instead.

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  BRAND_ROLES,
  LADDER,
  ladderValue,
  MIX_RATIOS,
  LINE_RATIOS,
  GLOBALS,
  BUTTON_N,
  SCROLL_N,
  SPINNER_N,
  SEPARATOR_N,
  SCROLL_RATIOS,
  SPINNER_VALS,
  GROUND_DARK,
  SURFACE_FAMILY,
  oklch,
} from "./formulas.js";
import { chooseForegrounds } from "./contrast.js";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "..");
const spec = JSON.parse(
  readFileSync(join(pkg, "tokens/default.spec.json"), "utf8"),
);
const schema = JSON.parse(
  readFileSync(join(pkg, "theme-spec.schema.json"), "utf8"),
);

const HEADER =
  "/* GENERATED by scripts/codegen.js from tokens/default.spec.json — do not edit by hand. */\n";
// Foregrounds chosen by APCA at build time (scripts/contrast.js): a light fill
// (e.g. warning) gets dark ink instead of an unreadable white.
const FOREGROUNDS = chooseForegrounds(spec);

function buildColor() {
  const c = spec.color;
  // Light block — every token at its light value. The shipped default theme
  // and the contract a consumer copies into their own [data-theme] block.
  const L = [];
  L.push("  color-scheme: light;", "");
  L.push("  /* Ground */");
  L.push(`  --background: ${oklch(c.background)};`);
  L.push(`  --foreground: ${oklch(c.foreground)};`);
  L.push(`  --neutral: ${oklch(c.neutral)};`, "");
  L.push(
    "  /* Inverted surface pair (e.g. a tooltip): background/foreground swapped */",
  );
  L.push("  --surface: var(--foreground);");
  L.push("  --surface-foreground: var(--background);", "");
  L.push(
    "  /* Brand roles — single-valued (background-independent) except accent */",
  );
  for (const role of BRAND_ROLES) {
    if (role === "accent") {
      L.push(`  --accent: ${oklch(c.accent)};`);
      L.push(`  --accent-foreground: ${FOREGROUNDS.accent};`);
    } else {
      L.push(`  --${role}: ${oklch(c[role])};`);
      L.push(`  --${role}-foreground: ${FOREGROUNDS[role]};`);
    }
  }
  L.push("");
  L.push(`  --ring: ${oklch(c.primary)};`);
  L.push(`  --link: ${oklch(c.primary)};`, "");
  L.push(
    "  /* Surface family — shadcn-compatible vocabulary, no interaction ladder */",
  );
  for (const [name, light] of SURFACE_FAMILY) {
    L.push(`  --${name}: ${light};`);
  }
  L.push("");
  L.push("  /* Destructive aliases danger (danger owns the ladder) */");
  L.push("  --destructive: var(--danger);");
  L.push("  --destructive-foreground: var(--danger-foreground);");

  // Dark block — only the tokens whose value flips. Brand roles, --neutral, the
  // inverted surface pair (var() refs that re-resolve against the dark ground)
  // and the destructive aliases inherit from the light block. Emitted AFTER the
  // light block so that on a dark element both :root and [data-theme="dark"]
  // match at equal specificity (0,1,0) and the dark values win on source order.
  const D = [];
  D.push("  color-scheme: dark;", "");
  D.push("  /* Ground */");
  D.push(`  --background: ${GROUND_DARK.background};`);
  D.push(`  --foreground: ${GROUND_DARK.foreground};`, "");
  D.push("  /* Accent flips with the ground */");
  D.push(`  --accent: ${GROUND_DARK.accent};`);
  D.push(`  --accent-foreground: ${GROUND_DARK["accent-foreground"]};`, "");
  D.push(`  --ring: ${GROUND_DARK.ring};`);
  D.push(`  --link: ${GROUND_DARK.link};`, "");
  D.push("  /* Surface family */");
  for (const [name, , dark] of SURFACE_FAMILY) {
    D.push(`  --${name}: ${dark};`);
  }

  const lightBlock = `:root,\n.light,\n[data-theme="light"] {\n${L.join("\n")}\n}`;
  const darkBlock = `.dark,\n[data-theme="dark"] {\n${D.join("\n")}\n}`;
  return `${HEADER}${lightBlock}\n\n${darkBlock}\n`;
}

function buildTheme() {
  const L = [];
  L.push(
    "  /* Global scalars — consumed across utilities, base, and components */",
  );
  for (const [k, v] of Object.entries(GLOBALS)) L.push(`  --${k}: ${v};`);
  L.push("", "  /* Interaction mix ratios — shared across every color role */");
  for (const [k, v] of Object.entries(MIX_RATIOS)) L.push(`  --${k}: ${v};`);
  L.push("", "  /* Neutral-derived line colors */");
  for (const [k, v] of Object.entries(LINE_RATIOS)) L.push(`  --${k}: ${v};`);
  L.push(
    "  --border-color: color-mix(in oklab, var(--neutral), transparent var(--mix-border-line));",
  );
  L.push(
    "  --separator-color: color-mix(in oklab, var(--neutral), transparent var(--mix-separator-line));",
  );
  L.push(
    "",
    "  /* Color ladder — generated per role × rung (single source: formulas.js) */",
  );
  for (const role of BRAND_ROLES) {
    for (const rung of LADDER)
      L.push(`  --${role}-${rung.suffix}: ${ladderValue(role, rung)};`);
  }
  L.push(
    "",
    "  /* Action geometry — button sizes (step count drives height, padding, radius) */",
  );
  for (const [s, n] of Object.entries(BUTTON_N))
    L.push(`  --button-n-${s}: ${n};`);
  for (const s of Object.keys(BUTTON_N))
    L.push(
      `  --button-h-${s}: calc(var(--size-action) * var(--button-n-${s}));`,
    );
  for (const s of Object.keys(BUTTON_N))
    L.push(
      `  --button-px-${s}: calc(var(--button-h-${s}) / 2 - var(--size-action));`,
    );
  for (const s of Object.keys(BUTTON_N))
    L.push(
      `  --button-radius-${s}: calc(var(--radius-action) * var(--button-n-${s}) / var(--button-n-md));`,
    );
  for (const s of Object.keys(BUTTON_N))
    L.push(`  --button-spinner-${s}: calc(var(--button-h-${s}) / 2);`);
  L.push("", "  /* Scroll-area geometry + thumb colors */");
  for (const [s, n] of Object.entries(SCROLL_N))
    L.push(`  --scroll-area-n-${s}: ${n};`);
  for (const s of Object.keys(SCROLL_N))
    L.push(
      `  --scroll-area-thickness-${s}: calc(var(--size-box) * var(--scroll-area-n-${s}));`,
    );
  for (const [k, v] of Object.entries(SCROLL_RATIOS)) L.push(`  --${k}: ${v};`);
  L.push(
    "  --scroll-thumb: color-mix(in oklab, var(--neutral) var(--mix-scroll-thumb), transparent);",
  );
  L.push(
    "  --scroll-thumb-hover: color-mix(in oklab, var(--neutral) var(--mix-scroll-thumb-hover), transparent);",
  );
  L.push("  --scroll-track: transparent;");
  L.push("", "  /* Spinner geometry + gradient (rides currentColor) */");
  for (const [s, n] of Object.entries(SPINNER_N))
    L.push(`  --spinner-n-${s}: ${n};`);
  for (const s of Object.keys(SPINNER_N))
    L.push(
      `  --spinner-size-${s}: calc(var(--size-feedback) * var(--spinner-n-${s}));`,
    );
  L.push(`  --spinner-arc: ${SPINNER_VALS["spinner-arc"]};`);
  L.push(`  --spinner-thickness: ${SPINNER_VALS["spinner-thickness"]};`);
  L.push(`  --mix-spinner-track: ${SPINNER_VALS["mix-spinner-track"]};`);
  L.push(
    "  --spinner-track: color-mix(in oklab, currentColor var(--mix-spinner-track), transparent);",
  );
  L.push(
    "  --spinner-image: conic-gradient(currentColor var(--spinner-arc), var(--spinner-track) 0);",
  );
  L.push(
    "  --spinner-mask: radial-gradient(farthest-side, transparent calc(100% - var(--spinner-thickness)), black 0);",
  );
  L.push("", "  /* Separator geometry */");
  L.push(`  --separator-n: ${SEPARATOR_N};`);
  L.push("  --separator-thickness: var(--border);");
  L.push("  --separator-length: calc(var(--size-box) * var(--separator-n));");
  L.push(
    "",
    "  /* Layout gap scale — shared by flex and grid, derived from --space */",
  );
  L.push("  --gap-xs: var(--space);");
  L.push("  --gap-sm: calc(var(--space) * 2);");
  L.push("  --gap-md: calc(var(--space) * 4);");
  L.push("  --gap-lg: calc(var(--space) * 6);");
  L.push("  --gap-xl: calc(var(--space) * 8);");
  const imports =
    '@import "./registered.css";\n@import "./border.css";\n@import "./color.css";\n@import "./radius.css";\n@import "./typography.css";';
  return `${HEADER}${imports}\n\n:root {\n${L.join("\n")}\n}\n`;
}

// Register the knob tokens with @property so the theme builder gets typed,
// animatable, guarded inputs — and browsers without light-dark() fall back to
// the (light) initial-value instead of an invalid declaration.
function buildRegistered() {
  const c = spec.color;
  const L = [];
  const reg = (name, syntax, init) =>
    L.push(
      `@property --${name} {\n  syntax: "${syntax}";\n  inherits: true;\n  initial-value: ${init};\n}`,
    );
  for (const role of BRAND_ROLES) {
    reg(role, "<color>", oklch(c[role]));
    reg(`${role}-foreground`, "<color>", FOREGROUNDS[role]);
  }
  reg("background", "<color>", oklch(c.background));
  reg("foreground", "<color>", oklch(c.foreground));
  reg("neutral", "<color>", oklch(c.neutral));
  for (const [name, light] of SURFACE_FAMILY) reg(name, "<color>", light);
  reg("space", "<length>", GLOBALS.space);
  reg("ring-width", "<length>", GLOBALS["ring-width"]);
  reg("ring-offset-width", "<length>", GLOBALS["ring-offset-width"]);
  reg("disabled-opacity", "<number>", GLOBALS["disabled-opacity"]);
  return `${HEADER}${L.join("\n\n")}\n`;
}

const title = (s) => s.charAt(0).toUpperCase() + s.slice(1);

// Builder manifest: the knobs a theme builder surfaces, with defaults from the
// spec and ranges from the schema (the one contract). Generated, not authored.
function buildKnobs() {
  const c = spec.color;
  const sp = schema.properties;
  const hueRange = (def) => {
    const h = schema.$defs[def]?.properties?.h;
    return h ? [h.minimum, h.maximum] : undefined;
  };
  const color = (id, statusDef) => {
    const k = {
      id,
      label: title(id),
      type: "oklch",
      cssVar: `--${id}`,
      default: c[id],
    };
    if (statusDef) k.hueRange = hueRange(statusDef);
    return k;
  };
  const groups = [
    {
      id: "color",
      label: "Colors",
      knobs: [
        color("primary"),
        color("secondary"),
        color("accent"),
        color("neutral"),
        color("background"),
        color("foreground"),
        color("danger", "statusDanger"),
        color("warning", "statusWarning"),
        color("success", "statusSuccess"),
        color("info", "statusInfo"),
      ],
    },
    {
      id: "geometry",
      label: "Geometry",
      knobs: [
        {
          id: "radiusScale",
          label: "Radius scale",
          type: "number",
          min: sp.radiusScale.minimum,
          max: sp.radiusScale.maximum,
          step: 0.05,
          default: spec.radiusScale,
        },
        {
          id: "border",
          label: "Border width",
          type: "dimension",
          default: spec.border,
        },
        {
          id: "density",
          label: "Density",
          type: "enum",
          options: sp.density.enum,
          default: spec.density,
        },
      ],
    },
    {
      id: "type",
      label: "Type",
      knobs: [
        {
          id: "typeScale",
          label: "Type scale",
          type: "number",
          min: sp.typeScale.minimum,
          max: sp.typeScale.maximum,
          step: 0.01,
          default: spec.typeScale,
        },
        {
          id: "fontSans",
          label: "Sans font",
          type: "font",
          default: spec.fontSans,
        },
        {
          id: "fontMono",
          label: "Mono font",
          type: "font",
          default: spec.fontMono,
        },
      ],
    },
    {
      id: "interaction",
      label: "Interaction",
      knobs: [
        {
          id: "intensity",
          label: "Mix intensity",
          type: "number",
          min: sp.intensity.minimum,
          max: sp.intensity.maximum,
          step: 0.05,
          default: spec.intensity,
        },
      ],
    },
  ];
  return `${JSON.stringify({ $generated: "scripts/codegen.js from default.spec.json + theme-spec.schema.json", groups }, null, 2)}\n`;
}

// The human + machine contract a person or an AI agent reads to author a theme.
function buildDesignMd() {
  const rungs = LADDER.map((r) => r.suffix).join(", ");
  const surfaces = SURFACE_FAMILY.map((s) => s[0])
    .filter((n) => !n.endsWith("-foreground"))
    .join(", ");
  const hue = (def) => {
    const h = schema.$defs[def].properties.h;
    return `${h.minimum}–${h.maximum}`;
  };
  return `---
$schema: ./theme-spec.schema.json
generated: true
pipeline: spec → validate (schema) → expand (formulas.js) → emit (color.css, theme.css, registered.css)
tier_a: [name, mode, color, radiusScale, border, density, typeScale, intensity, fontSans, fontMono]
derived_per_role: [${rungs}]
---

# Friday Design System — theme contract

This file is the human- and machine-readable contract for a Friday theme. A theme is a
small spec validated against \`theme-spec.schema.json\`; \`scripts/codegen.js\` expands it
through \`scripts/formulas.js\` into the full token system — no hand-authored color
values. Edit the spec or the formula table, never the generated CSS.

## Roles

- Brand roles (each owns a full interaction ladder): ${BRAND_ROLES.join(", ")}.
- Ground: background, foreground, neutral.
- Surface family (shadcn-compatible): ${surfaces}.
- \`destructive\` aliases \`danger\` (danger owns the ladder).

Every brand role derives ${LADDER.length} interaction rungs: ${rungs}.

## Status hue locks (enforced by the schema)

| role | hue band |
| --- | --- |
| danger | ${hue("statusDanger")} |
| warning | ${hue("statusWarning")} |
| success | ${hue("statusSuccess")} |
| info | ${hue("statusInfo")} |

An agent may tune a status role's L and C, but its hue stays in band — so red stays red.

## Invariants

- Every \`--<role>\` has a \`--<role>-foreground\` chosen for legible contrast; never set by hand.
- Button labels are five distinct sizes (xs < sm < md < lg < xl); no two adjacent sizes are pixel-identical.
- Dark mode is an explicit \`.dark, [data-theme="dark"]\` block (emitted after the light block), so the interaction ladder reflows per \`color-scheme\`.

## Worked example — "a calm fintech dark theme"

calm → low chroma (C ≤ 0.12) · fintech → blue family (hue 220–260) · dark → \`mode: "dark"\`.

\`\`\`json
{
  "name": "Calm Fintech",
  "mode": "dark",
  "color": {
    "primary": { "l": 0.62, "c": 0.11, "h": 245 },
    "neutral": { "l": 0.65, "c": 0.01, "h": 245 },
    "background": { "l": 0.17, "c": 0, "h": 0 },
    "foreground": { "l": 0.96, "c": 0, "h": 0 }
  },
  "radiusScale": 0.75
}
\`\`\`

Validate it against the schema, then run codegen to expand it into palette, ladder,
surfaces, and dark values.
`;
}

const cssOut = [
  "src/theme/registered.css",
  "src/theme/color.css",
  "src/theme/theme.css",
];
const docOut = ["tokens/knobs.json", "design.md"];
writeFileSync(join(pkg, cssOut[0]), buildRegistered());
writeFileSync(join(pkg, cssOut[1]), buildColor());
writeFileSync(join(pkg, cssOut[2]), buildTheme());
writeFileSync(join(pkg, docOut[0]), buildKnobs());
writeFileSync(join(pkg, docOut[1]), buildDesignMd());
// Format with Prettier so generated output matches the committed style, keeping
// `pnpm build` idempotent (.prettierignore is protected, so we self-format).
const all = [...cssOut, ...docOut].join(" ");
execSync(`pnpm exec prettier --write ${all}`, { cwd: pkg, stdio: "inherit" });
console.log(`codegen: wrote + formatted ${all}`);
