// Codegen: expand tokens/default.spec.json through formulas.js into the
// generated `--fri-*` token CSS. Run via `pnpm --filter @friday-sandbox/styles codegen`.
// Generated files are committed but hand-edits are overwritten — change the spec
// or scripts/formulas.js instead.
//
// Emits, all from one source (formulas.js):
//   src/theme/tokens.css      @layer theme — base per [data-theme] scope + the
//                             derived system under `:root, [data-theme]` so a
//                             nested scope recomputes its own color-mix.
//   src/theme/tailwind.css    UNLAYERED @theme inline — maps Tailwind's
//                             --color-* / --radius-* to the --fri-* tokens.
//   src/theme/registered.css  @property typing (static initial-value).
//   src/theme-template.css    the Tier-1 override starter a consumer copies.
//   design.md                 the human + machine contract.

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  P,
  BRAND_ROLES,
  LADDER,
  ladder,
  MIX_RATIOS,
  SURFACES,
  surface,
  surfaceForeground,
  FIELD_EXTRAS,
  TEXT_TIERS,
  textTier,
  BORDER_TIERS,
  borderTier,
  SCROLL_THUMB,
  POINTERS,
  RADIUS_SCALE,
  RADIUS_ARCHETYPE,
  SPACING_SCALE,
  DURATION,
  EASING,
  Z_INDEX,
  GLOBALS,
  BUTTON_N,
  SCROLL_N,
  SPINNER_N,
  SEPARATOR_N,
  SPINNER_VALS,
  GAP_SCALE,
  GROUND_DARK,
  oklch,
} from "./formulas.js";
import { chooseForegrounds } from "./contrast.js";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "..");
const spec = JSON.parse(
  readFileSync(join(pkg, "tokens/default.spec.json"), "utf8"),
);

const HEADER =
  "/* GENERATED by scripts/codegen.js from tokens/default.spec.json — do not edit by hand. */\n";
const FG = chooseForegrounds(spec);
const v = (name) => `var(${P}${name})`;
const decl = (name, value) => `  ${P}${name}: ${value};`;
const BORDER_NAME = {
  strong: "border-strong",
  default: "border",
  subtle: "border-subtle",
};

/** The Tier-1 base block: the small surface a consumer overrides. */
function baseLight() {
  const c = spec.color;
  const L = ["  color-scheme: light;", ""];
  L.push("  /* Ground */");
  L.push(decl("background", oklch(c.background)));
  L.push(decl("foreground", oklch(c.foreground)));
  L.push(decl("neutral", oklch(c.neutral)), "");
  L.push("  /* Brand and status roles (background-independent fills) */");
  for (const role of BRAND_ROLES) {
    L.push(decl(role, oklch(c[role])));
    L.push(decl(`${role}-foreground`, FG[role]));
  }
  L.push("");
  L.push(
    "  /* Focus ring — defaults to primary; override for an a11y focus colour */",
  );
  L.push(decl("ring", v("primary")), "");
  L.push("  /* Radius scale */");
  for (const [k, val] of Object.entries(RADIUS_SCALE))
    L.push(decl(`radius-${k}`, val));
  L.push("", "  /* Spacing scale */");
  for (const [k, val] of Object.entries(SPACING_SCALE))
    L.push(decl(`spacing-${k}`, val));
  L.push("", "  /* Type */");
  L.push(
    decl(
      "font-family-sans",
      spec.fontSans || "ui-sans-serif, system-ui, sans-serif",
    ),
  );
  L.push(
    decl(
      "font-family-mono",
      spec.fontMono || "ui-monospace, SFMono-Regular, Menlo, monospace",
    ),
  );
  L.push("", "  /* Motion */");
  for (const [k, val] of Object.entries(DURATION))
    L.push(decl(`duration-${k}`, val));
  for (const [k, val] of Object.entries(EASING))
    L.push(decl(`easing-${k}`, val));
  L.push("", "  /* Stacking */");
  for (const [k, val] of Object.entries(Z_INDEX)) L.push(decl(`z-${k}`, val));
  L.push("", "  /* Global scalars */");
  for (const [k, val] of Object.entries(GLOBALS)) L.push(decl(k, val));
  L.push(decl("size", "0.25rem"));
  return L.join("\n");
}

/** The dark block: only the tokens that flip with the ground. */
function baseDark() {
  const D = ["  color-scheme: dark;", ""];
  D.push("  /* Ground flips */");
  D.push(decl("background", GROUND_DARK.background));
  D.push(decl("foreground", GROUND_DARK.foreground), "");
  D.push("  /* Accent flips with the ground */");
  D.push(decl("accent", GROUND_DARK.accent));
  D.push(decl("accent-foreground", GROUND_DARK["accent-foreground"]));
  return D.join("\n");
}

/** The Tier-2 derived system — emitted per scope so nested themes recompute. */
function derived() {
  const D = [];
  D.push(
    "  /* Interaction mix ratios (shared; a future intensity knob scales these) */",
  );
  for (const [k, val] of Object.entries(MIX_RATIOS)) D.push(decl(k, val));
  D.push("", "  /* Interaction ladder — per role × rung */");
  for (const role of BRAND_ROLES)
    for (const rung of LADDER)
      D.push(decl(`${role}-${rung.suffix}`, ladder(role, rung.suffix)));
  D.push("", "  /* Surfaces (derived from the ground) */");
  for (const name of SURFACES) {
    D.push(decl(name, surface(name)));
    D.push(decl(`${name}-foreground`, surfaceForeground(name)));
  }
  D.push(decl("overlay", surface("overlay")));
  for (const [k, val] of Object.entries(FIELD_EXTRAS)) D.push(decl(k, val));
  D.push("", "  /* Text emphasis tiers */");
  for (const name of Object.keys(TEXT_TIERS))
    D.push(decl(`foreground-${name}`, textTier(name)));
  D.push("", "  /* Border / line tiers */");
  for (const name of Object.keys(BORDER_TIERS))
    D.push(decl(BORDER_NAME[name], borderTier(name)));
  for (const [k, val] of Object.entries(SCROLL_THUMB)) D.push(decl(k, val));
  D.push("", "  /* Pointers */");
  for (const [k, val] of Object.entries(POINTERS)) D.push(decl(k, val));
  D.push("", "  /* Archetype radii alias the t-shirt scale */");
  for (const [k, alias] of Object.entries(RADIUS_ARCHETYPE))
    D.push(decl(`radius-${k}`, v(`radius-${alias}`)));
  D.push("", "  /* Layout gap aliases the spacing scale */");
  for (const k of GAP_SCALE) D.push(decl(`gap-${k}`, v(`spacing-${k}`)));
  D.push("", "  /* Component geometry ramps */");
  for (const [s, n] of Object.entries(BUTTON_N))
    D.push(decl(`button-n-${s}`, `${n}`));
  for (const s of Object.keys(BUTTON_N))
    D.push(decl(`button-h-${s}`, `calc(${v("size")} * ${v(`button-n-${s}`)})`));
  for (const s of Object.keys(BUTTON_N))
    D.push(
      decl(`button-px-${s}`, `calc(${v(`button-h-${s}`)} / 2 - ${v("size")})`),
    );
  for (const s of Object.keys(BUTTON_N))
    D.push(
      decl(
        `button-radius-${s}`,
        `calc(${v("radius-action")} * ${v(`button-n-${s}`)} / ${v("button-n-md")})`,
      ),
    );
  for (const s of Object.keys(BUTTON_N))
    D.push(decl(`button-spinner-${s}`, `calc(${v(`button-h-${s}`)} / 2)`));
  for (const [s, n] of Object.entries(SCROLL_N))
    D.push(decl(`scroll-area-n-${s}`, `${n}`));
  for (const s of Object.keys(SCROLL_N))
    D.push(
      decl(
        `scroll-area-thickness-${s}`,
        `calc(${v("size")} * ${v(`scroll-area-n-${s}`)})`,
      ),
    );
  for (const [s, n] of Object.entries(SPINNER_N))
    D.push(decl(`spinner-n-${s}`, `${n}`));
  for (const s of Object.keys(SPINNER_N))
    D.push(
      decl(`spinner-size-${s}`, `calc(${v("size")} * ${v(`spinner-n-${s}`)})`),
    );
  for (const [k, val] of Object.entries(SPINNER_VALS)) D.push(decl(k, val));
  D.push(
    decl(
      "spinner-track",
      `color-mix(in oklab, currentColor ${v("mix-spinner-track")}, transparent)`,
    ),
  );
  D.push(
    decl(
      "spinner-image",
      `conic-gradient(currentColor ${v("spinner-arc")}, ${v("spinner-track")} 0)`,
    ),
  );
  D.push(
    decl(
      "spinner-mask",
      `radial-gradient(farthest-side, transparent calc(100% - ${v("spinner-thickness")}), black 0)`,
    ),
  );
  D.push(decl("separator-n", `${SEPARATOR_N}`));
  D.push(decl("separator-thickness", v("border-width")));
  D.push(decl("separator-length", `calc(${v("size")} * ${v("separator-n")})`));
  return D.join("\n");
}

function buildTokens() {
  const light = `:root,\n.light,\n[data-theme="light"] {\n${baseLight()}\n}`;
  const dark = `.dark,\n[data-theme="dark"] {\n${baseDark()}\n}`;
  const der = `:root,\n[data-theme] {\n${derived()}\n}`;
  return `${HEADER}@layer theme {\n${light}\n\n${dark}\n\n${der}\n}\n`;
}

/**
 * The Tailwind `--color-<utility>` map: each utility name a component references
 * (`bg-separator`, `text-primary`, …) paired with the `--fri-*` token it reads.
 * Most are identity; a few utility names differ from the token (separator).
 */
function colorMap() {
  const m = [
    ["background", "background"],
    ["foreground", "foreground"],
    ["neutral", "neutral"],
    ["ring", "ring"],
    ["link", "link"],
    ["overlay", "overlay"],
    ["border", "border"],
    ["border-strong", "border-strong"],
    ["border-subtle", "border-subtle"],
    ["separator", "border-subtle"],
    ["scroll-thumb", "scroll-thumb"],
    ["scroll-thumb-hover", "scroll-thumb-hover"],
    ["scroll-track", "scroll-track"],
    ["foreground-muted", "foreground-muted"],
    ["foreground-faint", "foreground-faint"],
  ];
  for (const role of BRAND_ROLES) {
    m.push([role, role], [`${role}-foreground`, `${role}-foreground`]);
    for (const rung of LADDER)
      m.push([`${role}-${rung.suffix}`, `${role}-${rung.suffix}`]);
  }
  for (const name of SURFACES)
    m.push([name, name], [`${name}-foreground`, `${name}-foreground`]);
  m.push(
    ["field-border-color", "field-border-color"],
    ["field-placeholder", "field-placeholder"],
  );
  return m;
}

/** UNLAYERED @theme inline so Tailwind v4 reads it at the theme-directive level. */
function buildTailwind() {
  const L = [];
  for (const [utility, token] of colorMap())
    L.push(`  --color-${utility}: var(${P}${token});`);
  for (const k of Object.keys(RADIUS_SCALE))
    L.push(`  --radius-${k}: var(${P}radius-${k});`);
  for (const k of Object.keys(SPACING_SCALE))
    L.push(`  --spacing-${k}: var(${P}spacing-${k});`);
  L.push(`  --font-sans: var(${P}font-family-sans);`);
  L.push(`  --font-mono: var(${P}font-family-mono);`);
  return `${HEADER}@theme inline {\n${L.join("\n")}\n}\n`;
}

/** @property typing for the base color tokens. Static initial-value (no var/color-mix). */
function buildRegistered() {
  const c = spec.color;
  const L = [];
  const reg = (name, init) =>
    L.push(
      `@property ${P}${name} {\n  syntax: "<color>";\n  inherits: true;\n  initial-value: ${init};\n}`,
    );
  for (const role of BRAND_ROLES) {
    reg(role, oklch(c[role]));
    reg(`${role}-foreground`, FG[role]);
  }
  reg("background", oklch(c.background));
  reg("foreground", oklch(c.foreground));
  reg("neutral", oklch(c.neutral));
  return `${HEADER}${L.join("\n\n")}\n`;
}

/** The Tier-1 override starter a consumer copies into their global CSS. */
function buildTemplate() {
  const c = spec.color;
  const line = (name, val) => `  ${P}${name}: ${val};`;
  const L = [];
  L.push("/* Friday theme override template — copy into your global CSS after");
  L.push(
    '   `@import "@friday-sandbox/styles"`. Set only these base tokens; the',
  );
  L.push(
    "   system derives the ladder, surfaces, and tiers from them. Override a",
  );
  L.push("   foreground together with its fill so the text stays legible. */");
  L.push("");
  L.push(':root,\n[data-theme="light"] {');
  L.push("  /* Brand */");
  for (const role of ["primary", "secondary", "accent"]) {
    L.push(line(role, oklch(c[role])));
    L.push(line(`${role}-foreground`, FG[role]));
  }
  L.push("  /* Status */");
  for (const role of ["info", "success", "warning", "danger"]) {
    L.push(line(role, oklch(c[role])));
    L.push(line(`${role}-foreground`, FG[role]));
  }
  L.push("  /* Ground */");
  L.push(line("background", oklch(c.background)));
  L.push(line("foreground", oklch(c.foreground)));
  L.push(line("neutral", oklch(c.neutral)));
  L.push("  /* Focus, geometry, type */");
  L.push(line("ring", "var(--fri-primary)"));
  L.push(line("radius-md", RADIUS_SCALE.md));
  L.push(line("border-width", GLOBALS["border-width"]));
  L.push("}");
  L.push("");
  L.push('.dark,\n[data-theme="dark"] {');
  L.push("  /* Only the ground flips; brand and status fills carry across. */");
  L.push(line("background", GROUND_DARK.background));
  L.push(line("foreground", GROUND_DARK.foreground));
  L.push("}");
  return `${L.join("\n")}\n`;
}

function buildDesignMd() {
  const rungs = LADDER.map((r) => r.suffix).join(", ");
  return `---
generated: true
namespace: --fri-*
pipeline: spec -> validate (schema) -> derive (formulas.js) -> emit (tokens.css, tailwind.css, registered.css)
---

# Friday Design System — token contract

Generated from \`tokens/default.spec.json\` through \`scripts/formulas.js\`. Every
token is \`--fri-*\` prefixed; every colour mix is \`color-mix(in oklab, …)\`. Edit
the spec or the formula table, never the generated CSS.

## Two tiers

- **Tier 1 (consumer base):** brand \`primary/secondary/accent\`, status \`info/success/warning/danger\` (each + \`-foreground\`); ground \`background/foreground/neutral\`; \`ring\`; the radius and spacing scales; type, motion, and z-index. A consumer sets these; the system derives the rest.
- **Tier 2 (derived):** the ${LADDER.length}-rung interaction ladder (${rungs}) per brand role; surfaces (card, popover, field, surface, surface-strong, inverse, overlay) derived from the ground; text tiers (foreground-muted, foreground-faint); border tiers (border-strong, border, border-subtle). Public and overridable, but names freeze only at the first stable release.

## Emission

Token definitions live in \`@layer theme\`; the derived system is emitted under
\`:root, [data-theme]\` so a nested \`[data-theme]\` scope recomputes its own
\`color-mix\` against that scope's ground. The \`@theme inline\` Tailwind map is
emitted unlayered in \`tailwind.css\`. \`@property\` registers the base colours as
progressive enhancement with a static \`initial-value\`.
`;
}

const out = {
  "src/theme/tokens.css": buildTokens(),
  "src/theme/tailwind.css": buildTailwind(),
  "src/theme/registered.css": buildRegistered(),
  "src/theme-template.css": buildTemplate(),
  "design.md": buildDesignMd(),
};
for (const [rel, content] of Object.entries(out))
  writeFileSync(join(pkg, rel), content);
const all = Object.keys(out).join(" ");
execSync(`pnpm exec prettier --write ${all}`, { cwd: pkg, stdio: "inherit" });
console.log(`codegen: wrote + formatted ${all}`);
