export const TYPOGRAPHY = [
  { value: "display-xxl", label: "Display XXL" },
  { value: "display-xl", label: "Display XL" },
  { value: "display-lg", label: "Display LG" },
  { value: "display-md", label: "Display MD" },
  { value: "display-sm", label: "Display SM" },
  { value: "body-lg", label: "Body LG" },
  { value: "body-lg-strong", label: "Body LG Strong" },
  { value: "body-md", label: "Body MD" },
  { value: "body-md-strong", label: "Body MD Strong" },
  { value: "body-sm", label: "Body SM" },
  { value: "body-sm-strong", label: "Body SM Strong" },
  { value: "body-xs", label: "Body XS" },
  { value: "body-xs-strong", label: "Body XS Strong" },
  { value: "label-lg", label: "Label LG" },
  { value: "label-md", label: "Label MD" },
  { value: "label-sm", label: "Label SM" },
  { value: "caption", label: "Caption" },
  { value: "caption-strong", label: "Caption Strong" },
  { value: "code", label: "Code" },
  { value: "inherit", label: "Inherit" },
] as const;
