export const paddingVariants = {
  p: {
    "2xs": "fri-p-2xs",
    xs: "fri-p-xs",
    sm: "fri-p-sm",
    md: "fri-p-md",
    lg: "fri-p-lg",
    xl: "fri-p-xl",
    "2xl": "fri-p-2xl",
    "3xl": "fri-p-3xl",
    "4xl": "fri-p-4xl",
  },
  px: {
    "2xs": "fri-px-2xs",
    xs: "fri-px-xs",
    sm: "fri-px-sm",
    md: "fri-px-md",
    lg: "fri-px-lg",
    xl: "fri-px-xl",
    "2xl": "fri-px-2xl",
    "3xl": "fri-px-3xl",
    "4xl": "fri-px-4xl",
  },
  py: {
    "2xs": "fri-py-2xs",
    xs: "fri-py-xs",
    sm: "fri-py-sm",
    md: "fri-py-md",
    lg: "fri-py-lg",
    xl: "fri-py-xl",
    "2xl": "fri-py-2xl",
    "3xl": "fri-py-3xl",
    "4xl": "fri-py-4xl",
  },
  pt: {
    "2xs": "fri-pt-2xs",
    xs: "fri-pt-xs",
    sm: "fri-pt-sm",
    md: "fri-pt-md",
    lg: "fri-pt-lg",
    xl: "fri-pt-xl",
    "2xl": "fri-pt-2xl",
    "3xl": "fri-pt-3xl",
    "4xl": "fri-pt-4xl",
  },
  pr: {
    "2xs": "fri-pr-2xs",
    xs: "fri-pr-xs",
    sm: "fri-pr-sm",
    md: "fri-pr-md",
    lg: "fri-pr-lg",
    xl: "fri-pr-xl",
    "2xl": "fri-pr-2xl",
    "3xl": "fri-pr-3xl",
    "4xl": "fri-pr-4xl",
  },
  pb: {
    "2xs": "fri-pb-2xs",
    xs: "fri-pb-xs",
    sm: "fri-pb-sm",
    md: "fri-pb-md",
    lg: "fri-pb-lg",
    xl: "fri-pb-xl",
    "2xl": "fri-pb-2xl",
    "3xl": "fri-pb-3xl",
    "4xl": "fri-pb-4xl",
  },
  pl: {
    "2xs": "fri-pl-2xs",
    xs: "fri-pl-xs",
    sm: "fri-pl-sm",
    md: "fri-pl-md",
    lg: "fri-pl-lg",
    xl: "fri-pl-xl",
    "2xl": "fri-pl-2xl",
    "3xl": "fri-pl-3xl",
    "4xl": "fri-pl-4xl",
  },
};

export const paddingSlotVariants = {
  p: {
    "2xs": { grid: paddingVariants.p["2xs"], item: paddingVariants.p["2xs"] },
    xs: { grid: paddingVariants.p.xs, item: paddingVariants.p.xs },
    sm: { grid: paddingVariants.p.sm, item: paddingVariants.p.sm },
    md: { grid: paddingVariants.p.md, item: paddingVariants.p.md },
    lg: { grid: paddingVariants.p.lg, item: paddingVariants.p.lg },
    xl: { grid: paddingVariants.p.xl, item: paddingVariants.p.xl },
    "2xl": { grid: paddingVariants.p["2xl"], item: paddingVariants.p["2xl"] },
    "3xl": { grid: paddingVariants.p["3xl"], item: paddingVariants.p["3xl"] },
    "4xl": { grid: paddingVariants.p["4xl"], item: paddingVariants.p["4xl"] },
  },
  px: {
    "2xs": { grid: paddingVariants.px["2xs"], item: paddingVariants.px["2xs"] },
    xs: { grid: paddingVariants.px.xs, item: paddingVariants.px.xs },
    sm: { grid: paddingVariants.px.sm, item: paddingVariants.px.sm },
    md: { grid: paddingVariants.px.md, item: paddingVariants.px.md },
    lg: { grid: paddingVariants.px.lg, item: paddingVariants.px.lg },
    xl: { grid: paddingVariants.px.xl, item: paddingVariants.px.xl },
    "2xl": { grid: paddingVariants.px["2xl"], item: paddingVariants.px["2xl"] },
    "3xl": { grid: paddingVariants.px["3xl"], item: paddingVariants.px["3xl"] },
    "4xl": { grid: paddingVariants.px["4xl"], item: paddingVariants.px["4xl"] },
  },
  py: {
    "2xs": { grid: paddingVariants.py["2xs"], item: paddingVariants.py["2xs"] },
    xs: { grid: paddingVariants.py.xs, item: paddingVariants.py.xs },
    sm: { grid: paddingVariants.py.sm, item: paddingVariants.py.sm },
    md: { grid: paddingVariants.py.md, item: paddingVariants.py.md },
    lg: { grid: paddingVariants.py.lg, item: paddingVariants.py.lg },
    xl: { grid: paddingVariants.py.xl, item: paddingVariants.py.xl },
    "2xl": { grid: paddingVariants.py["2xl"], item: paddingVariants.py["2xl"] },
    "3xl": { grid: paddingVariants.py["3xl"], item: paddingVariants.py["3xl"] },
    "4xl": { grid: paddingVariants.py["4xl"], item: paddingVariants.py["4xl"] },
  },
  pt: {
    "2xs": { grid: paddingVariants.pt["2xs"], item: paddingVariants.pt["2xs"] },
    xs: { grid: paddingVariants.pt.xs, item: paddingVariants.pt.xs },
    sm: { grid: paddingVariants.pt.sm, item: paddingVariants.pt.sm },
    md: { grid: paddingVariants.pt.md, item: paddingVariants.pt.md },
    lg: { grid: paddingVariants.pt.lg, item: paddingVariants.pt.lg },
    xl: { grid: paddingVariants.pt.xl, item: paddingVariants.pt.xl },
    "2xl": { grid: paddingVariants.pt["2xl"], item: paddingVariants.pt["2xl"] },
    "3xl": { grid: paddingVariants.pt["3xl"], item: paddingVariants.pt["3xl"] },
    "4xl": { grid: paddingVariants.pt["4xl"], item: paddingVariants.pt["4xl"] },
  },
  pr: {
    "2xs": { grid: paddingVariants.pr["2xs"], item: paddingVariants.pr["2xs"] },
    xs: { grid: paddingVariants.pr.xs, item: paddingVariants.pr.xs },
    sm: { grid: paddingVariants.pr.sm, item: paddingVariants.pr.sm },
    md: { grid: paddingVariants.pr.md, item: paddingVariants.pr.md },
    lg: { grid: paddingVariants.pr.lg, item: paddingVariants.pr.lg },
    xl: { grid: paddingVariants.pr.xl, item: paddingVariants.pr.xl },
    "2xl": { grid: paddingVariants.pr["2xl"], item: paddingVariants.pr["2xl"] },
    "3xl": { grid: paddingVariants.pr["3xl"], item: paddingVariants.pr["3xl"] },
    "4xl": { grid: paddingVariants.pr["4xl"], item: paddingVariants.pr["4xl"] },
  },
  pb: {
    "2xs": { grid: paddingVariants.pb["2xs"], item: paddingVariants.pb["2xs"] },
    xs: { grid: paddingVariants.pb.xs, item: paddingVariants.pb.xs },
    sm: { grid: paddingVariants.pb.sm, item: paddingVariants.pb.sm },
    md: { grid: paddingVariants.pb.md, item: paddingVariants.pb.md },
    lg: { grid: paddingVariants.pb.lg, item: paddingVariants.pb.lg },
    xl: { grid: paddingVariants.pb.xl, item: paddingVariants.pb.xl },
    "2xl": { grid: paddingVariants.pb["2xl"], item: paddingVariants.pb["2xl"] },
    "3xl": { grid: paddingVariants.pb["3xl"], item: paddingVariants.pb["3xl"] },
    "4xl": { grid: paddingVariants.pb["4xl"], item: paddingVariants.pb["4xl"] },
  },
  pl: {
    "2xs": { grid: paddingVariants.pl["2xs"], item: paddingVariants.pl["2xs"] },
    xs: { grid: paddingVariants.pl.xs, item: paddingVariants.pl.xs },
    sm: { grid: paddingVariants.pl.sm, item: paddingVariants.pl.sm },
    md: { grid: paddingVariants.pl.md, item: paddingVariants.pl.md },
    lg: { grid: paddingVariants.pl.lg, item: paddingVariants.pl.lg },
    xl: { grid: paddingVariants.pl.xl, item: paddingVariants.pl.xl },
    "2xl": { grid: paddingVariants.pl["2xl"], item: paddingVariants.pl["2xl"] },
    "3xl": { grid: paddingVariants.pl["3xl"], item: paddingVariants.pl["3xl"] },
    "4xl": { grid: paddingVariants.pl["4xl"], item: paddingVariants.pl["4xl"] },
  },
};

export const gapVariants = {
  gap: {
    "2xs": "fri-gap-2xs",
    xs: "fri-gap-xs",
    sm: "fri-gap-sm",
    md: "fri-gap-md",
    lg: "fri-gap-lg",
    xl: "fri-gap-xl",
    "2xl": "fri-gap-2xl",
    "3xl": "fri-gap-3xl",
    "4xl": "fri-gap-4xl",
  },
  gapX: {
    "2xs": "fri-gap-x-2xs",
    xs: "fri-gap-x-xs",
    sm: "fri-gap-x-sm",
    md: "fri-gap-x-md",
    lg: "fri-gap-x-lg",
    xl: "fri-gap-x-xl",
    "2xl": "fri-gap-x-2xl",
    "3xl": "fri-gap-x-3xl",
    "4xl": "fri-gap-x-4xl",
  },
  gapY: {
    "2xs": "fri-gap-y-2xs",
    xs: "fri-gap-y-xs",
    sm: "fri-gap-y-sm",
    md: "fri-gap-y-md",
    lg: "fri-gap-y-lg",
    xl: "fri-gap-y-xl",
    "2xl": "fri-gap-y-2xl",
    "3xl": "fri-gap-y-3xl",
    "4xl": "fri-gap-y-4xl",
  },
};

export const gapSlotVariants = {
  gap: {
    "2xs": { grid: gapVariants.gap["2xs"] },
    xs: { grid: gapVariants.gap.xs },
    sm: { grid: gapVariants.gap.sm },
    md: { grid: gapVariants.gap.md },
    lg: { grid: gapVariants.gap.lg },
    xl: { grid: gapVariants.gap.xl },
    "2xl": { grid: gapVariants.gap["2xl"] },
    "3xl": { grid: gapVariants.gap["3xl"] },
    "4xl": { grid: gapVariants.gap["4xl"] },
  },
  gapX: {
    "2xs": { grid: gapVariants.gapX["2xs"] },
    xs: { grid: gapVariants.gapX.xs },
    sm: { grid: gapVariants.gapX.sm },
    md: { grid: gapVariants.gapX.md },
    lg: { grid: gapVariants.gapX.lg },
    xl: { grid: gapVariants.gapX.xl },
    "2xl": { grid: gapVariants.gapX["2xl"] },
    "3xl": { grid: gapVariants.gapX["3xl"] },
    "4xl": { grid: gapVariants.gapX["4xl"] },
  },
  gapY: {
    "2xs": { grid: gapVariants.gapY["2xs"] },
    xs: { grid: gapVariants.gapY.xs },
    sm: { grid: gapVariants.gapY.sm },
    md: { grid: gapVariants.gapY.md },
    lg: { grid: gapVariants.gapY.lg },
    xl: { grid: gapVariants.gapY.xl },
    "2xl": { grid: gapVariants.gapY["2xl"] },
    "3xl": { grid: gapVariants.gapY["3xl"] },
    "4xl": { grid: gapVariants.gapY["4xl"] },
  },
};
