export const paddingVariants = {
  p: {
    "2xs": "fri-p-2xs",
    xs: "fri-p-xs",
    sm: "fri-p-sm",
    md: "fri-p-md",
    lg: "fri-p-lg",
    xl: "fri-p-xl",
    "2xl": "fri-p-2xl",
    "3xl": "fri-p-3xl",
    "4xl": "fri-p-4xl",
  },
  px: {
    "2xs": "fri-px-2xs",
    xs: "fri-px-xs",
    sm: "fri-px-sm",
    md: "fri-px-md",
    lg: "fri-px-lg",
    xl: "fri-px-xl",
    "2xl": "fri-px-2xl",
    "3xl": "fri-px-3xl",
    "4xl": "fri-px-4xl",
  },
  py: {
    "2xs": "fri-py-2xs",
    xs: "fri-py-xs",
    sm: "fri-py-sm",
    md: "fri-py-md",
    lg: "fri-py-lg",
    xl: "fri-py-xl",
    "2xl": "fri-py-2xl",
    "3xl": "fri-py-3xl",
    "4xl": "fri-py-4xl",
  },
  pt: {
    "2xs": "fri-pt-2xs",
    xs: "fri-pt-xs",
    sm: "fri-pt-sm",
    md: "fri-pt-md",
    lg: "fri-pt-lg",
    xl: "fri-pt-xl",
    "2xl": "fri-pt-2xl",
    "3xl": "fri-pt-3xl",
    "4xl": "fri-pt-4xl",
  },
  pr: {
    "2xs": "fri-pr-2xs",
    xs: "fri-pr-xs",
    sm: "fri-pr-sm",
    md: "fri-pr-md",
    lg: "fri-pr-lg",
    xl: "fri-pr-xl",
    "2xl": "fri-pr-2xl",
    "3xl": "fri-pr-3xl",
    "4xl": "fri-pr-4xl",
  },
  pb: {
    "2xs": "fri-pb-2xs",
    xs: "fri-pb-xs",
    sm: "fri-pb-sm",
    md: "fri-pb-md",
    lg: "fri-pb-lg",
    xl: "fri-pb-xl",
    "2xl": "fri-pb-2xl",
    "3xl": "fri-pb-3xl",
    "4xl": "fri-pb-4xl",
  },
  pl: {
    "2xs": "fri-pl-2xs",
    xs: "fri-pl-xs",
    sm: "fri-pl-sm",
    md: "fri-pl-md",
    lg: "fri-pl-lg",
    xl: "fri-pl-xl",
    "2xl": "fri-pl-2xl",
    "3xl": "fri-pl-3xl",
    "4xl": "fri-pl-4xl",
  },
};

export const gapVariants = {
  gap: {
    "2xs": "fri-gap-2xs",
    xs: "fri-gap-xs",
    sm: "fri-gap-sm",
    md: "fri-gap-md",
    lg: "fri-gap-lg",
    xl: "fri-gap-xl",
    "2xl": "fri-gap-2xl",
    "3xl": "fri-gap-3xl",
    "4xl": "fri-gap-4xl",
  },
  gapX: {
    "2xs": "fri-gap-x-2xs",
    xs: "fri-gap-x-xs",
    sm: "fri-gap-x-sm",
    md: "fri-gap-x-md",
    lg: "fri-gap-x-lg",
    xl: "fri-gap-x-xl",
    "2xl": "fri-gap-x-2xl",
    "3xl": "fri-gap-x-3xl",
    "4xl": "fri-gap-x-4xl",
  },
  gapY: {
    "2xs": "fri-gap-y-2xs",
    xs: "fri-gap-y-xs",
    sm: "fri-gap-y-sm",
    md: "fri-gap-y-md",
    lg: "fri-gap-y-lg",
    xl: "fri-gap-y-xl",
    "2xl": "fri-gap-y-2xl",
    "3xl": "fri-gap-y-3xl",
    "4xl": "fri-gap-y-4xl",
  },
};
